# Generated by Django 5.0.7 on 2024-07-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id_equipamento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('fabricante', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('num_serie', models.CharField(max_length=255)),
                ('data_compra', models.DateField()),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
