# Generated by Django 5.0.7 on 2024-07-16 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_desafio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipamentos',
            new_name='Equipamento',
        ),
    ]
