# Generated by Django 5.0.7 on 2024-07-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_desafio', '0002_rename_equipamentos_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='fabricante',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='modelo',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='num_serie',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.TextField(max_length=255),
        ),
    ]
