# Generated by Django 5.0.7 on 2024-07-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_desafio', '0003_alter_equipamento_fabricante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
