# Generated by Django 5.0.7 on 2024-07-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_desafio', '0004_alter_equipamento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='fabricante',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
