# Generated by Django 5.0.7 on 2024-07-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_desafio', '0005_alter_equipamento_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='modelo',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='num_serie',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
