# Generated by Django 5.0.7 on 2024-07-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_desafio', '0006_alter_equipamento_modelo_alter_equipamento_num_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='data_compra',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
