# Generated by Django 5.0.7 on 2024-07-18 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_desafio', '0007_alter_equipamento_data_compra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='data_compra',
            new_name='data_de_compra',
        ),
        migrations.RenameField(
            model_name='equipamento',
            old_name='num_serie',
            new_name='numero_de_serie',
        ),
        migrations.RenameField(
            model_name='equipamento',
            old_name='valor_compra',
            new_name='valor_da_compra',
        ),
    ]
